name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Beta
      run: rustup install beta
    - name: Build
      run: cargo +beta build --verbose
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Beta
      run: rustup install beta
    - name: Run tests
      run: cargo +beta test --verbose
